export const TYPE_ABSTRACT_BASE_COMPONENT = "TYPE_ABSTRACT_BASE_COMPONENT";

export const TYPE_VOWL_PARSER = "TYPE_VOWL_PARSER";
export const TYPE_SPARQL_PARSER = "TYPE_SPARQL_PARSER";

// MODEL MODELS
export const TYPE_ABSTRACT_MODEL = "TYPE_ABSTRACT_MODEL";
export const TYPE_RESOURCE_RELATION_MODEL = "TYPE_RESOURCE_RELATION_MODEL";
export const TYPE_VERTEX_EDGE_MODEL = "TYPE_VERTEX_EDGE_MODEL";
export const TYPE_NODE_LINK_MODEL = "TYPE_NODE_LINK_MODEL";

// // MAPPERS
export const TYPE_VERTEX_EDGE_MAPPER = "TYPE_VERTEX_EDGE_MAPPER";
export const TYPE_NODE_LINK_MAPPER = "TYPE_NODE_LINK_MAPPER";

// export const TYPE_VOWL_VE2NL_MAPPER = "TYPE_VOWL_VE2NL_MAPPER";
